version: '3.7'
volumes: 
  # Declares a volume named grafana_data
  grafana_data: {}
networks:
  # Declares a network named front-tier
  front-tier:
  # Declares a network named back-tier
  back-tier:
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - back-tier
  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - "3000:3000"
    networks:
      - back-tier
      - front-tier
    restart: always